#!/bin/sh

clashnivo_service_firewall_init() {
   CLASHNIVO_FIREWALL_BACKEND="nftables"
   CLASHNIVO_FIREWALL_FAMILY="inet"
   CLASHNIVO_FIREWALL_TABLE="fw4"
   CLASHNIVO_FIREWALL_CHAIN_PREFIX="clashnivo"
   CLASHNIVO_FIREWALL_COMMENT_PREFIX="ClashNivo"
   CLASHNIVO_FIREWALL_COMMENT_REGEX="clashnivo|ClashNivo"

   CLASHNIVO_FIREWALL_CHAIN_MAIN="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}"
   CLASHNIVO_FIREWALL_CHAIN_OUTPUT="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_output"
   CLASHNIVO_FIREWALL_CHAIN_MANGLE="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_mangle"
   CLASHNIVO_FIREWALL_CHAIN_MANGLE_OUTPUT="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_mangle_output"
   CLASHNIVO_FIREWALL_CHAIN_POST="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_post"
   CLASHNIVO_FIREWALL_CHAIN_WAN_INPUT="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_wan_input"
   CLASHNIVO_FIREWALL_CHAIN_DNS_REDIRECT="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_dns_redirect"
   CLASHNIVO_FIREWALL_CHAIN_UPNP="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_upnp"
   CLASHNIVO_FIREWALL_CHAIN_V6="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_v6"
   CLASHNIVO_FIREWALL_CHAIN_V6_OUTPUT="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_output_v6"
   CLASHNIVO_FIREWALL_CHAIN_V6_MANGLE="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_mangle_v6"
   CLASHNIVO_FIREWALL_CHAIN_V6_MANGLE_OUTPUT="${CLASHNIVO_FIREWALL_CHAIN_PREFIX}_mangle_output_v6"
   CLASHNIVO_FIREWALL_CHAIN_DNS_HIJACK="${CLASHNIVO_FIREWALL_COMMENT_PREFIX} DNS Hijack"
   CLASHNIVO_FIREWALL_CHAIN_BYPASS_COMPAT="${CLASHNIVO_FIREWALL_COMMENT_PREFIX} Bypass Gateway Compatible"
}

clashnivo_service_firewall_apply() {
   set_firewall "$@"
}

clashnivo_service_firewall_cleanup() {
   revert_firewall "$@"
}

clashnivo_service_firewall_comment_regex() {
   printf '%s' "${CLASHNIVO_FIREWALL_COMMENT_REGEX}"
}
