#!/bin/sh

clashnivo_service_init_state() {
   CLASHNIVO_STATE_DIR="/tmp"
   CLASHNIVO_RUNTIME_PREFIX="${CLASHNIVO_STATE_DIR}/clashnivo"
   CLASHNIVO_TMP_ETC_DIR="/tmp/etc/clashnivo"
   CLASHNIVO_SERVICE_NAME="clashnivo"
   CLASHNIVO_WATCHDOG_SERVICE_NAME="clashnivo-watchdog"

   CLASHNIVO_LOG_FILE="${CLASHNIVO_RUNTIME_PREFIX}.log"
   CLASHNIVO_CORE_LOG_FILE="${CLASHNIVO_STATE_DIR}/clash.log"
   CLASHNIVO_UPDATE_LOG_FILE="${CLASHNIVO_RUNTIME_PREFIX}_updates.log"
   CLASHNIVO_SUBSCRIPTION_UPDATE_LOG_FILE="${CLASHNIVO_RUNTIME_PREFIX}_subscription_refresh.log"
   CLASHNIVO_COMMAND_LOCK_DIR="${CLASHNIVO_RUNTIME_PREFIX}_command.lock"
   CLASHNIVO_COMMAND_LOCK_PID_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/pid"
   CLASHNIVO_COMMAND_LOCK_CONTEXT_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/context"
   CLASHNIVO_COMMAND_LOCK_STARTED_AT_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/started_at"
   CLASHNIVO_COMMAND_LOCK_KIND_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/kind"
   CLASHNIVO_COMMAND_LOCK_TARGET_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/target"
   CLASHNIVO_COMMAND_LOCK_CANCELABLE_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/cancelable"
   CLASHNIVO_COMMAND_LOCK_TIMEOUT_AT_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/timeout_at"
   CLASHNIVO_COMMAND_LOCK_STATUS_PATH_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/status_path"
   CLASHNIVO_COMMAND_LOCK_LOG_PATH_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/log_path"
   CLASHNIVO_COMMAND_LOCK_FINAL_STATE_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/final_state"
   CLASHNIVO_COMMAND_LOCK_FINAL_MESSAGE_FILE="${CLASHNIVO_COMMAND_LOCK_DIR}/final_message"
   CLASHNIVO_START_LOG_FILE="${CLASHNIVO_RUNTIME_PREFIX}_start.log"
   CLASHNIVO_CHANGE_FILE="${CLASHNIVO_RUNTIME_PREFIX}.change"
   CLASHNIVO_DEBUG_LOG_FILE="${CLASHNIVO_RUNTIME_PREFIX}_debug.log"
   CLASHNIVO_ANNOUNCEMENT_FILE="${CLASHNIVO_RUNTIME_PREFIX}_announcement"
   CLASHNIVO_LAST_VERSION_FILE="${CLASHNIVO_RUNTIME_PREFIX}_last_version"
   CLASHNIVO_BLOCKED_REASON_FILE="${CLASHNIVO_RUNTIME_PREFIX}_blocked_reason"
   CLASHNIVO_PACKAGE_UPDATE_STATUS_FILE="${CLASHNIVO_RUNTIME_PREFIX}_package_update_status"
   CLASHNIVO_PACKAGE_UPDATE_LOG_FILE="${CLASHNIVO_PACKAGE_UPDATE_STATUS_FILE}.log"
   CLASHNIVO_CORE_UPDATE_STATUS_FILE="${CLASHNIVO_RUNTIME_PREFIX}_core_update_status"
   CLASHNIVO_CORE_UPDATE_LOG_FILE="${CLASHNIVO_CORE_UPDATE_STATUS_FILE}.log"
   CLASHNIVO_CORE_LATEST_CACHE_FILE="${CLASHNIVO_RUNTIME_PREFIX}_core_latest_version"
   CLASHNIVO_ASSETS_UPDATE_STATUS_FILE="${CLASHNIVO_RUNTIME_PREFIX}_assets_update_status"
   CLASHNIVO_ASSETS_UPDATE_LOG_FILE="${CLASHNIVO_ASSETS_UPDATE_STATUS_FILE}.log"
   CLASHNIVO_ASSETS_UPDATE_STATUS_DIR="${CLASHNIVO_RUNTIME_PREFIX}_asset_updates"
   CLASHNIVO_DASHBOARD_UPDATE_STATUS_DIR="${CLASHNIVO_RUNTIME_PREFIX}_dashboard_updates"
   CLASHNIVO_RUNTIME_STATE_DIR="${CLASHNIVO_RUNTIME_PREFIX}_runtime"
   CLASHNIVO_RUNTIME_DNS_APPLIED_FILE="${CLASHNIVO_RUNTIME_STATE_DIR}/dns_applied"
   CLASHNIVO_RUNTIME_FIREWALL_APPLIED_FILE="${CLASHNIVO_RUNTIME_STATE_DIR}/firewall_applied"
   CLASHNIVO_RUNTIME_START_FAILED_FILE="${CLASHNIVO_RUNTIME_STATE_DIR}/start_failed"

   # Compatibility aliases for inherited scripts that still expect generic names.
   LOG_FILE="${CLASHNIVO_LOG_FILE}"
   CORE_LOG_FILE="${CLASHNIVO_CORE_LOG_FILE}"
   UPDATE_LOG_FILE="${CLASHNIVO_UPDATE_LOG_FILE}"
   SUBSCRIPTION_UPDATE_LOG_FILE="${CLASHNIVO_SUBSCRIPTION_UPDATE_LOG_FILE}"
   COMMAND_LOCK_DIR="${CLASHNIVO_COMMAND_LOCK_DIR}"
   COMMAND_LOCK_PID_FILE="${CLASHNIVO_COMMAND_LOCK_PID_FILE}"
   COMMAND_LOCK_CONTEXT_FILE="${CLASHNIVO_COMMAND_LOCK_CONTEXT_FILE}"
   COMMAND_LOCK_STARTED_AT_FILE="${CLASHNIVO_COMMAND_LOCK_STARTED_AT_FILE}"
   COMMAND_LOCK_KIND_FILE="${CLASHNIVO_COMMAND_LOCK_KIND_FILE}"
   COMMAND_LOCK_TARGET_FILE="${CLASHNIVO_COMMAND_LOCK_TARGET_FILE}"
   COMMAND_LOCK_CANCELABLE_FILE="${CLASHNIVO_COMMAND_LOCK_CANCELABLE_FILE}"
   COMMAND_LOCK_TIMEOUT_AT_FILE="${CLASHNIVO_COMMAND_LOCK_TIMEOUT_AT_FILE}"
   COMMAND_LOCK_STATUS_PATH_FILE="${CLASHNIVO_COMMAND_LOCK_STATUS_PATH_FILE}"
   COMMAND_LOCK_LOG_PATH_FILE="${CLASHNIVO_COMMAND_LOCK_LOG_PATH_FILE}"
   COMMAND_LOCK_FINAL_STATE_FILE="${CLASHNIVO_COMMAND_LOCK_FINAL_STATE_FILE}"
   COMMAND_LOCK_FINAL_MESSAGE_FILE="${CLASHNIVO_COMMAND_LOCK_FINAL_MESSAGE_FILE}"
   START_LOG="${CLASHNIVO_START_LOG_FILE}"
   CHANGE_TRACK_FILE="${CLASHNIVO_CHANGE_FILE}"
   DEBUG_LOG_FILE="${CLASHNIVO_DEBUG_LOG_FILE}"
   ANNOUNCEMENT_FILE="${CLASHNIVO_ANNOUNCEMENT_FILE}"
   LAST_VERSION_FILE="${CLASHNIVO_LAST_VERSION_FILE}"
   BLOCKED_REASON_FILE="${CLASHNIVO_BLOCKED_REASON_FILE}"
   PACKAGE_UPDATE_STATUS_FILE="${CLASHNIVO_PACKAGE_UPDATE_STATUS_FILE}"
   PACKAGE_UPDATE_LOG_FILE="${CLASHNIVO_PACKAGE_UPDATE_LOG_FILE}"
   CORE_UPDATE_STATUS_FILE="${CLASHNIVO_CORE_UPDATE_STATUS_FILE}"
   CORE_UPDATE_LOG_FILE="${CLASHNIVO_CORE_UPDATE_LOG_FILE}"
   CORE_LATEST_CACHE_FILE="${CLASHNIVO_CORE_LATEST_CACHE_FILE}"
   ASSETS_UPDATE_STATUS_FILE="${CLASHNIVO_ASSETS_UPDATE_STATUS_FILE}"
   ASSETS_UPDATE_LOG_FILE="${CLASHNIVO_ASSETS_UPDATE_LOG_FILE}"
}

clashnivo_service_runtime_state_ensure_dir() {
   mkdir -p "${CLASHNIVO_RUNTIME_STATE_DIR}" 2>/dev/null
}

clashnivo_service_runtime_state_mark() {
   local marker="${1:-}"

   [ -n "${marker}" ] || return 1
   clashnivo_service_runtime_state_ensure_dir || return 1
   : > "${marker}"
}

clashnivo_service_runtime_state_mark_dns_applied() {
   clashnivo_service_runtime_state_mark "${CLASHNIVO_RUNTIME_DNS_APPLIED_FILE}"
}

clashnivo_service_runtime_state_mark_firewall_applied() {
   clashnivo_service_runtime_state_mark "${CLASHNIVO_RUNTIME_FIREWALL_APPLIED_FILE}"
}

clashnivo_service_runtime_state_mark_start_failed() {
   local reason="${1:-start_failed}"

   clashnivo_service_runtime_state_ensure_dir || return 1
   printf '%s\n' "${reason}" > "${CLASHNIVO_RUNTIME_START_FAILED_FILE}"
}

clashnivo_service_runtime_state_dns_applied() {
   [ -f "${CLASHNIVO_RUNTIME_DNS_APPLIED_FILE}" ]
}

clashnivo_service_runtime_state_firewall_applied() {
   [ -f "${CLASHNIVO_RUNTIME_FIREWALL_APPLIED_FILE}" ]
}

clashnivo_service_runtime_state_start_failed() {
   [ -f "${CLASHNIVO_RUNTIME_START_FAILED_FILE}" ]
}

clashnivo_service_runtime_state_start_failed_reason() {
   [ -f "${CLASHNIVO_RUNTIME_START_FAILED_FILE}" ] && sed -n '1p' "${CLASHNIVO_RUNTIME_START_FAILED_FILE}" 2>/dev/null
}

clashnivo_service_runtime_state_clear_start_failed() {
   rm -f "${CLASHNIVO_RUNTIME_START_FAILED_FILE}"
}

clashnivo_service_runtime_state_clear_network() {
   rm -f \
      "${CLASHNIVO_RUNTIME_DNS_APPLIED_FILE}" \
      "${CLASHNIVO_RUNTIME_FIREWALL_APPLIED_FILE}"
}

clashnivo_service_runtime_state_reset() {
   rm -rf "${CLASHNIVO_RUNTIME_STATE_DIR}"
}

clashnivo_service_clear_disabled_runtime_state() {
   rm -rf \
      /tmp/clash_last_version \
      "${LAST_VERSION_FILE}" \
      "${BLOCKED_REASON_FILE}" \
      "${PACKAGE_UPDATE_STATUS_FILE}" \
      "${PACKAGE_UPDATE_LOG_FILE}" \
      "${CHANGE_TRACK_FILE}" \
      "${DEBUG_LOG_FILE}" \
      "${ANNOUNCEMENT_FILE}"
}
