#!/bin/sh

clashnivo_service_init_state() {
   CLASHNIVO_STATE_DIR="/tmp"
   CLASHNIVO_RUNTIME_PREFIX="${CLASHNIVO_STATE_DIR}/clashnivo"
   CLASHNIVO_TMP_ETC_DIR="/tmp/etc/clashnivo"
   CLASHNIVO_SERVICE_NAME="clashnivo"
   CLASHNIVO_WATCHDOG_SERVICE_NAME="clashnivo-watchdog"

   CLASHNIVO_LOG_FILE="${CLASHNIVO_RUNTIME_PREFIX}.log"
   CLASHNIVO_START_LOG_FILE="${CLASHNIVO_RUNTIME_PREFIX}_start.log"
   CLASHNIVO_CHANGE_FILE="${CLASHNIVO_RUNTIME_PREFIX}.change"
   CLASHNIVO_DEBUG_LOG_FILE="${CLASHNIVO_RUNTIME_PREFIX}_debug.log"
   CLASHNIVO_ANNOUNCEMENT_FILE="${CLASHNIVO_RUNTIME_PREFIX}_announcement"
   CLASHNIVO_LAST_VERSION_FILE="${CLASHNIVO_RUNTIME_PREFIX}_last_version"
   CLASHNIVO_BLOCKED_REASON_FILE="${CLASHNIVO_RUNTIME_PREFIX}_blocked_reason"
   CLASHNIVO_PACKAGE_UPDATE_STATUS_FILE="${CLASHNIVO_RUNTIME_PREFIX}_package_update_status"
   CLASHNIVO_PACKAGE_UPDATE_LOG_FILE="${CLASHNIVO_PACKAGE_UPDATE_STATUS_FILE}.log"
   CLASHNIVO_CORE_UPDATE_STATUS_FILE="${CLASHNIVO_RUNTIME_PREFIX}_core_update_status"
   CLASHNIVO_CORE_UPDATE_LOG_FILE="${CLASHNIVO_CORE_UPDATE_STATUS_FILE}.log"
   CLASHNIVO_CORE_LATEST_CACHE_FILE="${CLASHNIVO_RUNTIME_PREFIX}_core_latest_version"
   CLASHNIVO_ASSETS_UPDATE_STATUS_FILE="${CLASHNIVO_RUNTIME_PREFIX}_assets_update_status"
   CLASHNIVO_ASSETS_UPDATE_LOG_FILE="${CLASHNIVO_ASSETS_UPDATE_STATUS_FILE}.log"
   CLASHNIVO_ASSETS_UPDATE_STATUS_DIR="${CLASHNIVO_RUNTIME_PREFIX}_asset_updates"

   # Compatibility aliases for inherited scripts that still expect generic names.
   LOG_FILE="${CLASHNIVO_LOG_FILE}"
   START_LOG="${CLASHNIVO_START_LOG_FILE}"
   CHANGE_TRACK_FILE="${CLASHNIVO_CHANGE_FILE}"
   DEBUG_LOG_FILE="${CLASHNIVO_DEBUG_LOG_FILE}"
   ANNOUNCEMENT_FILE="${CLASHNIVO_ANNOUNCEMENT_FILE}"
   LAST_VERSION_FILE="${CLASHNIVO_LAST_VERSION_FILE}"
   BLOCKED_REASON_FILE="${CLASHNIVO_BLOCKED_REASON_FILE}"
   PACKAGE_UPDATE_STATUS_FILE="${CLASHNIVO_PACKAGE_UPDATE_STATUS_FILE}"
   PACKAGE_UPDATE_LOG_FILE="${CLASHNIVO_PACKAGE_UPDATE_LOG_FILE}"
   CORE_UPDATE_STATUS_FILE="${CLASHNIVO_CORE_UPDATE_STATUS_FILE}"
   CORE_UPDATE_LOG_FILE="${CLASHNIVO_CORE_UPDATE_LOG_FILE}"
   CORE_LATEST_CACHE_FILE="${CLASHNIVO_CORE_LATEST_CACHE_FILE}"
   ASSETS_UPDATE_STATUS_FILE="${CLASHNIVO_ASSETS_UPDATE_STATUS_FILE}"
   ASSETS_UPDATE_LOG_FILE="${CLASHNIVO_ASSETS_UPDATE_LOG_FILE}"
}

clashnivo_service_clear_disabled_runtime_state() {
   rm -rf \
      /tmp/clash_last_version \
      "${LAST_VERSION_FILE}" \
      "${BLOCKED_REASON_FILE}" \
      "${PACKAGE_UPDATE_STATUS_FILE}" \
      "${PACKAGE_UPDATE_LOG_FILE}" \
      "${CHANGE_TRACK_FILE}" \
      "${DEBUG_LOG_FILE}" \
      "${ANNOUNCEMENT_FILE}"
}
